//LocalizedConstants.js
import {LocalizationString} from 'react-native-easy-localization-and-rtl';
const strings = LocalizationString({
  en: {
    languages: 'Languages',
    popular: 'Popular',
    routes: 'Routes',
    trackYourFlight: 'Track your flight',
    timatic: `Timatic delivers airlines accurate information based
    on the passenger’s`,
    nationality: 'Nationality',
    destination: 'Destination',
    passport: 'Passport',
    transitPoints: 'Transit Points',
    visas: 'Visas',
    welcomeFaiyaz: 'Welcome Faiyaz!',
    flight: 'Flight',
    hotels: 'Hotels',
    assistance: 'Assistance',
    trending: 'Trending',
    stayNearBy: 'Stay Near By',
    topDestinations: 'Top Destinations',
    searchFlights: 'Search flights',
    roundTrip: 'Round Trip',
    oneWay: 'One Way',
    multiCity: 'Multi-City',
    searchFlights: 'Search flights',
    recentlySearched: 'Recently Searched',
    from: 'From',
    to: 'To',
    departure: 'Departure',
    return: 'X Return',
    travellersClass: 'Travellers & Class',
    adult: 'Adult',
    children: 'Children',
    infant: 'Infant',
    economy: 'Economy',
    business: 'Business',
    firstClass: 'First Class',
    select: 'Select',
    cabinClass: 'Cabin Class',
    done: 'Done',
    addFlight: 'Add Flight',
    addReturn: 'Add Return?',
    topOrigins: 'Top Origins',
    cheapest: 'Cheapest',
    fastest: 'Fastest',
    best: 'Best',
    refundable: 'Refundable',
    seats: 'Seats',
    left: 'Left',
    departing: 'Departing',
    details: 'Details',
    returning: 'Returning',
    moreFlightOptions: 'More Flight Options',
    clear: 'Clear',
    sortFilterYourResults: 'Sort & Filter Your Results',
    sortBy: 'SortBy',
    filter: 'Filter',
    modifySearch: 'Modify Search',
    departureEarliest: 'Departure (Earliest)',
    departureLatest: 'Departure (Latest)',
    arrivalEarliest: 'Arrival (Earliest)',
    arrivalLatest: 'Arrival (Latest)',
    durationShortest: 'Duration (Shortest)',
    durationLongest: 'Duration (Longest)',
    priceHighest: 'Price (Highest)',
    priceLowest: 'Price (Lowest)',
    totalDuration: 'Total Duration',
    checkIn: 'Check In',
    cabin: 'Cabin',
    flexibleFlightOption: 'Flexible Flight Option',
    selectYourOnwardFlight: 'Select your onward flight',
    reviewYourFlightToDubai: 'Review your flight to Dubai',
    flightDetails: 'Flight Details',
    fareDetails: 'Fare Details',
    fareRules: 'Fare Rules',
    terminal: 'Terminal',
    fare: 'Fare',
    taxesFee: 'Taxes & Fee',
    grandTotal: 'Grand Total',
    taxesFeesIncluded: 'Taxes and fees Included',
    flightLongFareRules: 'Flight Long Fare Rules',
    ticketsNonRefundable: 'Tickets are non-refundable',
    fareRulesText1:
      'We Kindly remind that you may need visa for the following countries: United Arab Emirates.',
    fareRulesText2: 'Additional baggage fee may apply,',
    clickHere: 'click here',
    forMoreInfo: 'for more information.',
    termsPolicies: 'Terms & Policies',
    penalties: 'Penalties',
    minimumStay: 'Minimum Stay',
    maximumStay: 'Maximum Stay',
    seasonality: 'Seasonality',
    blackoutDate: 'Blackout Date',
    searchHotels: 'Search Hotels',
    searchDestinationName: 'Search Destination, City or Hotel Name',
    checkOut: 'Check-Out',
    roomsGuests: 'Rooms & Guests',
    recommended: 'Recommended',
    deals: 'Deals',
    starsHighest: 'Stars (Highest)',
    expediaRating: 'Expedia Rating',
  },
  ar: {
    languages: 'اللغات',
    routes: 'طرق',
    popular: 'شائع',
    trackYourFlight: 'تتبع رحلتك',
    timatic: `Timatic يسلم شركات الطيران معلومات دقيقة على أساس
    على الركاب`,
    nationality: 'جنسية',
    destination: 'الوجهة',
    passport: 'جواز سفر',
    transitPoints: 'نقاط العبور',
    visas: 'التأشيرات',
    welcomeFaiyaz: 'مرحبا بكم فياز!',
    flight: 'طيران',
    hotels: 'فندق',
    assistance: 'المساعدة',
    trending: 'الشائع',
    stayNearBy: 'ابق بالقرب من',
    topDestinations: 'أفضل الوجهات',
    searchFlights: 'بحث الرحلات الجوية',
    roundTrip: 'جولة',
    oneWay: 'طريقة واحدة',
    multiCity: 'مدينة متعددة',
    recentlySearched: 'بحثت مؤخرا',
    from: 'من',
    to: 'ل',
    departure: 'مقال',
    return: 'عودة X',
    travellersClass: 'المسافرون والطبقة',
    adult: 'الكبار',
    children: 'أطفال',
    infant: 'رضيع',
    economy: 'اقتصاد',
    business: 'اعمال',
    firstClass: 'الصف الأول',
    select: 'يختار',
    cabinClass: 'فئة المقصورة',
    done: 'فعله',
    addFlight: 'أضف رحلة',
    addReturn: 'إضافة العودة؟',
    topOrigins: 'أعلى الأصول',
    cheapest: 'أرخص',
    fastest: 'أسرع',
    best: 'الأفضل',
    refundable: 'مستردة',
    seats: 'مقاعد',
    left: 'اليسار',
    departing: 'المغادرة',
    details: 'تفاصيل',
    returning: 'عودة',
    moreFlightOptions: 'المزيد من خيارات الطيران',
    clear: 'صافي',
    sortFilterYourResults: 'فرز وتصفية النتائج الخاصة بك',
    sortBy: 'صنف حسب',
    filter: 'منقي',
    modifySearch: 'تعديل البحث',
    departureEarliest: 'المغادرة (أقرب وقت ممكن)',
    departureLatest: 'المغادرة (الأحدث)',
    arrivalEarliest: 'وصول (أقرب)',
    arrivalLatest: 'الوصول (الأحدث)',
    durationShortest: 'المدة (الأقصر)',
    durationLongest: 'المدة (الأطول)',
    priceHighest: 'السعر (الاعلى)',
    priceLowest: 'السعر (الأدنى)',
    totalDuration: 'المدة الإجمالية',
    checkIn: 'تحقق في',
    cabin: 'الطائرة',
    flexibleFlightOption: 'خيار طيران مرن',
    selectYourOnwardFlight: 'حدد رحلتك القادمة',
    reviewYourFlightToDubai: 'راجع رحلتك إلى دبي',
    flightDetails: 'تفاصيل الرحلة',
    fareDetails: 'تفاصيل الأجرة',
    fareRules: 'قوانين عادلة',
    terminal: 'صالة',
    fare: 'أجرة',
    taxesFee: 'الضرائب والرسوم',
    grandTotal: 'المجموع الإجمالي',
    taxesFeesIncluded: 'شامل الضرائب والرسوم',
    flightLongFareRules: 'قواعد أسعار الرحلات الطويلة',
    ticketsNonRefundable: 'التذاكر غير قابلة للاسترداد',
    fareRulesText1:
      'نود أن نذكر أنك قد تحتاج إلى تأشيرة للدول التالية: الإمارات العربية المتحدة.',
    fareRulesText2: 'قد يتم تطبيق رسوم أمتعة إضافية ،',
    clickHere: 'انقر هنا',
    forMoreInfo: 'للمزيد من  معلومة.',
    termsPolicies: 'سياسات الشروط',
    penalties: 'ضربات الجزاء',
    minimumStay: 'الحد الأدنى للإقامة',
    maximumStay: 'أقصى قدر من البقاء',
    seasonality: 'الموسمية',
    blackoutDate: 'تاريخ الحجب',
    searchHotels: 'البحث عن الفنادق',
    searchDestinationName: 'ابحث عن الوجهة أو المدينة أو اسم الفندق',
    checkOut: 'الدفع',
    roomsGuests: 'الغرف والضيوف',
    recommended: 'موصى به',
    deals: 'صفقات',
    starsHighest: 'النجوم (الأعلى)',
    expediaRating: 'تصنيف اكسبيديا',
  },
});

export {strings};
