//LocalizedConstants.js
import {LocalizationString} from 'react-native-easy-localization-and-rtl';
const strings = LocalizationString({
  en: {
    languages: 'Languages',
    popular: 'Popular',
    routes: 'Routes',
    trackYourFlight: 'Track your flight',
    timatic: `Timatic delivers airlines accurate information based
    on the passenger’s`,
    nationality: 'Nationality',
    destination: 'Destination',
    passport: 'Passport',
    transitPoints: 'Transit Points',
    visas: 'Visas',
    welcomeFaiyaz: 'Welcome Faiyaz!',
    flight: 'Flight',
    hotels: 'Hotels',
    assistance: 'Assistance',
    trending: 'Trending',
    stayNearBy: 'Stay Near By',
    topDestinations: 'Top Destinations',
    searchFlights: 'Search flights',
    roundTrip: 'Round Trip',
    oneWay: 'One Way',
    multiCity: 'Multi-City',
    searchFlights: 'Search flights',
    recentlySearched: 'Recently Searched',
    from: 'From',
    to: 'To',
    departure: 'Departure',
    return: 'X Return',
    travellersClass: 'Travellers & Class',
    adult: 'Adult',
    children: 'Children',
    infant: 'Infant',
    economy: 'Economy',
    business: 'Business',
    firstClass: 'First Class',
    select: 'Select',
    cabinClass: 'Cabin Class',
    done: 'Done',
    addFlight: 'Add Flight',
    addReturn: 'Add Return?',
    topOrigins: 'Top Origins',
  },
  ar: {
    languages: 'اللغات',
    routes: 'طرق',
    popular: 'شائع',
    trackYourFlight: 'تتبع رحلتك',
    timatic: `Timatic يسلم شركات الطيران معلومات دقيقة على أساس
    على الركاب`,
    nationality: 'جنسية',
    destination: 'الوجهة',
    passport: 'جواز سفر',
    transitPoints: 'نقاط العبور',
    visas: 'التأشيرات',
    welcomeFaiyaz: 'مرحبا بكم فياز!',
    flight: 'طيران',
    hotels: 'فندق',
    assistance: 'المساعدة',
    trending: 'الشائع',
    stayNearBy: 'ابق بالقرب من',
    topDestinations: 'أفضل الوجهات',
    searchFlights: 'بحث الرحلات الجوية',
    roundTrip: 'جولة',
    oneWay: 'طريقة واحدة',
    multiCity: 'مدينة متعددة',
    recentlySearched: 'بحثت مؤخرا',
    from: 'من',
    to: 'ل',
    departure: 'مقال',
    return: 'عودة X',
    travellersClass: 'المسافرون والطبقة',
    adult: 'الكبار',
    children: 'أطفال',
    infant: 'رضيع',
    economy: 'اقتصاد',
    business: 'اعمال',
    firstClass: 'الصف الأول',
    select: 'يختار',
    cabinClass: 'فئة المقصورة',
    done: 'فعله',
    addFlight: 'أضف رحلة',
    addReturn: 'إضافة العودة؟',
    topOrigins: 'أعلى الأصول',
  },
});

export {strings};
